// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(OpenHealthAsn1FFI)
import OpenHealthAsn1FFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_asn1_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_asn1_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAsn1Initialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * FFI-friendly ASN.1 tag representation.
 */
public protocol Asn1TagProtocol: AnyObject, Sendable {
    
    func `class`()  -> Asn1TagClass
    
    func form()  -> Asn1TagForm
    
    func number()  -> UInt32
    
}
/**
 * FFI-friendly ASN.1 tag representation.
 */
open class Asn1Tag: Asn1TagProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_asn1tag(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_asn1tag(handle, $0) }
    }

    

    
open func `class`() -> Asn1TagClass  {
    return try!  FfiConverterTypeAsn1TagClass_lift(try! rustCall() {
    uniffi_asn1_fn_method_asn1tag_class_(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func form() -> Asn1TagForm  {
    return try!  FfiConverterTypeAsn1TagForm_lift(try! rustCall() {
    uniffi_asn1_fn_method_asn1tag_form(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func number() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_asn1_fn_method_asn1tag_number(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsn1Tag: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Asn1Tag

    public static func lift(_ handle: UInt64) throws -> Asn1Tag {
        return Asn1Tag(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Asn1Tag) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Asn1Tag {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Asn1Tag, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1Tag_lift(_ handle: UInt64) throws -> Asn1Tag {
    return try FfiConverterTypeAsn1Tag.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1Tag_lower(_ value: Asn1Tag) -> UInt64 {
    return FfiConverterTypeAsn1Tag.lower(value)
}






/**
 * Parsed CV certificate (application tag `7F21`).
 */
public protocol CvCertificateProtocol: AnyObject, Sendable {
    
    func body()  -> CvCertificateBody
    
    func signature()  -> Data
    
}
/**
 * Parsed CV certificate (application tag `7F21`).
 */
open class CvCertificate: CvCertificateProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvcertificate(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvcertificate(handle, $0) }
    }

    

    
open func body() -> CvCertificateBody  {
    return try!  FfiConverterTypeCvCertificateBody_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificate_body(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func signature() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificate_signature(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvCertificate: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvCertificate

    public static func lift(_ handle: UInt64) throws -> CvCertificate {
        return CvCertificate(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvCertificate) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvCertificate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvCertificate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificate_lift(_ handle: UInt64) throws -> CvCertificate {
    return try FfiConverterTypeCvCertificate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificate_lower(_ value: CvCertificate) -> UInt64 {
    return FfiConverterTypeCvCertificate.lower(value)
}






/**
 * Parsed CV certificate body.
 */
public protocol CvCertificateBodyProtocol: AnyObject, Sendable {
    
    func certificateEffectiveDate()  -> CvCertificateDate
    
    func certificateExpirationDate()  -> CvCertificateDate
    
    func certificateExtensions()  -> CvCertificateExtensions?
    
    func certificateHolderAuthorizationTemplate()  -> CvChat
    
    func certificateHolderReference()  -> Data
    
    func certificationAuthorityReference()  -> Data
    
    func profileIdentifier()  -> UInt8
    
    func publicKey()  -> CvPublicKey
    
}
/**
 * Parsed CV certificate body.
 */
open class CvCertificateBody: CvCertificateBodyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvcertificatebody(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvcertificatebody(handle, $0) }
    }

    

    
open func certificateEffectiveDate() -> CvCertificateDate  {
    return try!  FfiConverterTypeCvCertificateDate_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certificate_effective_date(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func certificateExpirationDate() -> CvCertificateDate  {
    return try!  FfiConverterTypeCvCertificateDate_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certificate_expiration_date(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func certificateExtensions() -> CvCertificateExtensions?  {
    return try!  FfiConverterOptionTypeCvCertificateExtensions.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certificate_extensions(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func certificateHolderAuthorizationTemplate() -> CvChat  {
    return try!  FfiConverterTypeCvChat_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certificate_holder_authorization_template(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func certificateHolderReference() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certificate_holder_reference(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func certificationAuthorityReference() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_certification_authority_reference(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func profileIdentifier() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_profile_identifier(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func publicKey() -> CvPublicKey  {
    return try!  FfiConverterTypeCvPublicKey_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatebody_public_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvCertificateBody: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvCertificateBody

    public static func lift(_ handle: UInt64) throws -> CvCertificateBody {
        return CvCertificateBody(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvCertificateBody) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvCertificateBody {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvCertificateBody, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateBody_lift(_ handle: UInt64) throws -> CvCertificateBody {
    return try FfiConverterTypeCvCertificateBody.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateBody_lower(_ value: CvCertificateBody) -> UInt64 {
    return FfiConverterTypeCvCertificateBody.lower(value)
}






/**
 * A CVC date encoded as digits `YYMMDD`.
 */
public protocol CvCertificateDateProtocol: AnyObject, Sendable {
    
    func day()  -> UInt8
    
    func month()  -> UInt8
    
    func year()  -> UInt8
    
}
/**
 * A CVC date encoded as digits `YYMMDD`.
 */
open class CvCertificateDate: CvCertificateDateProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvcertificatedate(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvcertificatedate(handle, $0) }
    }

    

    
open func day() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatedate_day(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func month() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatedate_month(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func year() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificatedate_year(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvCertificateDate: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvCertificateDate

    public static func lift(_ handle: UInt64) throws -> CvCertificateDate {
        return CvCertificateDate(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvCertificateDate) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvCertificateDate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvCertificateDate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateDate_lift(_ handle: UInt64) throws -> CvCertificateDate {
    return try FfiConverterTypeCvCertificateDate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateDate_lower(_ value: CvCertificateDate) -> UInt64 {
    return FfiConverterTypeCvCertificateDate.lower(value)
}






/**
 * Optional extensions carried in the certificate body.
 */
public protocol CvCertificateExtensionsProtocol: AnyObject, Sendable {
    
    func templates()  -> [CvDiscretionaryDataTemplate]
    
}
/**
 * Optional extensions carried in the certificate body.
 */
open class CvCertificateExtensions: CvCertificateExtensionsProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvcertificateextensions(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvcertificateextensions(handle, $0) }
    }

    

    
open func templates() -> [CvDiscretionaryDataTemplate]  {
    return try!  FfiConverterSequenceTypeCvDiscretionaryDataTemplate.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvcertificateextensions_templates(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvCertificateExtensions: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvCertificateExtensions

    public static func lift(_ handle: UInt64) throws -> CvCertificateExtensions {
        return CvCertificateExtensions(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvCertificateExtensions) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvCertificateExtensions {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvCertificateExtensions, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateExtensions_lift(_ handle: UInt64) throws -> CvCertificateExtensions {
    return try FfiConverterTypeCvCertificateExtensions.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvCertificateExtensions_lower(_ value: CvCertificateExtensions) -> UInt64 {
    return FfiConverterTypeCvCertificateExtensions.lower(value)
}






/**
 * Certificate Holder Authorization Template (CHAT).
 */
public protocol CvChatProtocol: AnyObject, Sendable {
    
    func relativeAuthorization()  -> Data
    
    func terminalTypeOid()  -> String
    
}
/**
 * Certificate Holder Authorization Template (CHAT).
 */
open class CvChat: CvChatProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvchat(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvchat(handle, $0) }
    }

    

    
open func relativeAuthorization() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvchat_relative_authorization(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func terminalTypeOid() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvchat_terminal_type_oid(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvChat: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvChat

    public static func lift(_ handle: UInt64) throws -> CvChat {
        return CvChat(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvChat) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvChat {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvChat, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvChat_lift(_ handle: UInt64) throws -> CvChat {
    return try FfiConverterTypeCvChat.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvChat_lower(_ value: CvChat) -> UInt64 {
    return FfiConverterTypeCvChat.lower(value)
}






/**
 * One discretionary data template within [`CvCertificateExtensions`].
 */
public protocol CvDiscretionaryDataTemplateProtocol: AnyObject, Sendable {
    
    func extensionData()  -> [CvExtensionField]
    
    func extensionIdOid()  -> String
    
}
/**
 * One discretionary data template within [`CvCertificateExtensions`].
 */
open class CvDiscretionaryDataTemplate: CvDiscretionaryDataTemplateProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvdiscretionarydatatemplate(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvdiscretionarydatatemplate(handle, $0) }
    }

    

    
open func extensionData() -> [CvExtensionField]  {
    return try!  FfiConverterSequenceTypeCvExtensionField.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvdiscretionarydatatemplate_extension_data(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func extensionIdOid() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvdiscretionarydatatemplate_extension_id_oid(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvDiscretionaryDataTemplate: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvDiscretionaryDataTemplate

    public static func lift(_ handle: UInt64) throws -> CvDiscretionaryDataTemplate {
        return CvDiscretionaryDataTemplate(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvDiscretionaryDataTemplate) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvDiscretionaryDataTemplate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvDiscretionaryDataTemplate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvDiscretionaryDataTemplate_lift(_ handle: UInt64) throws -> CvDiscretionaryDataTemplate {
    return try FfiConverterTypeCvDiscretionaryDataTemplate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvDiscretionaryDataTemplate_lower(_ value: CvDiscretionaryDataTemplate) -> UInt64 {
    return FfiConverterTypeCvDiscretionaryDataTemplate.lower(value)
}






/**
 * A raw extension field inside a discretionary data template.
 */
public protocol CvExtensionFieldProtocol: AnyObject, Sendable {
    
    func tag()  -> Asn1Tag
    
    func value()  -> Data
    
}
/**
 * A raw extension field inside a discretionary data template.
 */
open class CvExtensionField: CvExtensionFieldProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvextensionfield(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvextensionfield(handle, $0) }
    }

    

    
open func tag() -> Asn1Tag  {
    return try!  FfiConverterTypeAsn1Tag_lift(try! rustCall() {
    uniffi_asn1_fn_method_cvextensionfield_tag(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func value() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvextensionfield_value(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvExtensionField: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvExtensionField

    public static func lift(_ handle: UInt64) throws -> CvExtensionField {
        return CvExtensionField(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvExtensionField) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvExtensionField {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvExtensionField, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvExtensionField_lift(_ handle: UInt64) throws -> CvExtensionField {
    return try FfiConverterTypeCvExtensionField.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvExtensionField_lower(_ value: CvExtensionField) -> UInt64 {
    return FfiConverterTypeCvExtensionField.lower(value)
}






/**
 * CV certificate public key information.
 */
public protocol CvPublicKeyProtocol: AnyObject, Sendable {
    
    func keyData()  -> Data
    
    func keyOid()  -> String
    
}
/**
 * CV certificate public key information.
 */
open class CvPublicKey: CvPublicKeyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_asn1_fn_clone_cvpublickey(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_asn1_fn_free_cvpublickey(handle, $0) }
    }

    

    
open func keyData() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvpublickey_key_data(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func keyOid() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_asn1_fn_method_cvpublickey_key_oid(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCvPublicKey: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CvPublicKey

    public static func lift(_ handle: UInt64) throws -> CvPublicKey {
        return CvPublicKey(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CvPublicKey) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CvPublicKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CvPublicKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvPublicKey_lift(_ handle: UInt64) throws -> CvPublicKey {
    return try FfiConverterTypeCvPublicKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCvPublicKey_lower(_ value: CvPublicKey) -> UInt64 {
    return FfiConverterTypeCvPublicKey.lower(value)
}




/**
 * UniFFI error type for `asn1` operations.
 */
public enum Asn1FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Decode(reason: String
    )
    case InvalidArgument(reason: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Asn1FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsn1FfiError: FfiConverterRustBuffer {
    typealias SwiftType = Asn1FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Asn1FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Decode(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidArgument(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Asn1FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Decode(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidArgument(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1FfiError_lift(_ buf: RustBuffer) throws -> Asn1FfiError {
    return try FfiConverterTypeAsn1FfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1FfiError_lower(_ value: Asn1FfiError) -> RustBuffer {
    return FfiConverterTypeAsn1FfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-friendly tag class.
 */

public enum Asn1TagClass: Equatable, Hashable {
    
    case universal
    case application
    case contextSpecific
    case `private`



}

#if compiler(>=6)
extension Asn1TagClass: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsn1TagClass: FfiConverterRustBuffer {
    typealias SwiftType = Asn1TagClass

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Asn1TagClass {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .universal
        
        case 2: return .application
        
        case 3: return .contextSpecific
        
        case 4: return .`private`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Asn1TagClass, into buf: inout [UInt8]) {
        switch value {
        
        
        case .universal:
            writeInt(&buf, Int32(1))
        
        
        case .application:
            writeInt(&buf, Int32(2))
        
        
        case .contextSpecific:
            writeInt(&buf, Int32(3))
        
        
        case .`private`:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1TagClass_lift(_ buf: RustBuffer) throws -> Asn1TagClass {
    return try FfiConverterTypeAsn1TagClass.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1TagClass_lower(_ value: Asn1TagClass) -> RustBuffer {
    return FfiConverterTypeAsn1TagClass.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-friendly tag form (`primitive` vs `constructed`).
 */

public enum Asn1TagForm: Equatable, Hashable {
    
    case primitive
    case constructed



}

#if compiler(>=6)
extension Asn1TagForm: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAsn1TagForm: FfiConverterRustBuffer {
    typealias SwiftType = Asn1TagForm

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Asn1TagForm {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .primitive
        
        case 2: return .constructed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Asn1TagForm, into buf: inout [UInt8]) {
        switch value {
        
        
        case .primitive:
            writeInt(&buf, Int32(1))
        
        
        case .constructed:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1TagForm_lift(_ buf: RustBuffer) throws -> Asn1TagForm {
    return try FfiConverterTypeAsn1TagForm.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAsn1TagForm_lower(_ value: Asn1TagForm) -> RustBuffer {
    return FfiConverterTypeAsn1TagForm.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCvCertificateExtensions: FfiConverterRustBuffer {
    typealias SwiftType = CvCertificateExtensions?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCvCertificateExtensions.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCvCertificateExtensions.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCvDiscretionaryDataTemplate: FfiConverterRustBuffer {
    typealias SwiftType = [CvDiscretionaryDataTemplate]

    public static func write(_ value: [CvDiscretionaryDataTemplate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCvDiscretionaryDataTemplate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CvDiscretionaryDataTemplate] {
        let len: Int32 = try readInt(&buf)
        var seq = [CvDiscretionaryDataTemplate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCvDiscretionaryDataTemplate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCvExtensionField: FfiConverterRustBuffer {
    typealias SwiftType = [CvExtensionField]

    public static func write(_ value: [CvExtensionField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCvExtensionField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CvExtensionField] {
        let len: Int32 = try readInt(&buf)
        var seq = [CvExtensionField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCvExtensionField.read(from: &buf))
        }
        return seq
    }
}
public func parseCvCertificate(data: Data)throws  -> CvCertificate  {
    return try  FfiConverterTypeCvCertificate_lift(try rustCallWithError(FfiConverterTypeAsn1FfiError_lift) {
    uniffi_asn1_fn_func_parse_cv_certificate(
        FfiConverterData.lower(data),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_asn1_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_asn1_checksum_func_parse_cv_certificate() != 27521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_asn1tag_class_() != 33233) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_asn1tag_form() != 57046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_asn1tag_number() != 11812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificate_body() != 28115) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificate_signature() != 49055) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certificate_effective_date() != 51143) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certificate_expiration_date() != 9444) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certificate_extensions() != 43358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certificate_holder_authorization_template() != 16982) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certificate_holder_reference() != 36169) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_certification_authority_reference() != 5793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_profile_identifier() != 3802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatebody_public_key() != 15168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatedate_day() != 36367) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatedate_month() != 20952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificatedate_year() != 58480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvcertificateextensions_templates() != 41802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvchat_relative_authorization() != 61506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvchat_terminal_type_oid() != 5289) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvdiscretionarydatatemplate_extension_data() != 42478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvdiscretionarydatatemplate_extension_id_oid() != 15136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvextensionfield_tag() != 18409) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvextensionfield_value() != 58963) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvpublickey_key_data() != 13574) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_asn1_checksum_method_cvpublickey_key_oid() != 46983) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAsn1Initialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all