name: "PullRequest Checks"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: gradle
          distribution: 'temurin'
      - name: Install dependencies
        shell: bash
        run: |
          file /lib/x86_64-linux-gnu/libc++.so
          sudo apt-get update
          sudo apt-get install -y cmake swig ninja-build clang clang-tools libc++-dev libc++abi-dev
          file /lib/x86_64-linux-gnu/libc++.so
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Android NDK
        shell: bash
        run: |
          sdkmanager "ndk;27.2.12479018"
          sdkmanager "cmake;3.31.6"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: KTLint Check
        run: |
          ./gradlew ktlintCheck

      - name: Detekt Check
        run: |
          ./gradlew detekt

      - name: Test
        shell: bash
        env:
          CC: clang
          CXX: clang++
          CXXFLAGS: --stdlib=libc++
        run: |
          ./gradlew jvmTest

